# Generated by Django 5.0.1 on 2024-02-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardGames',
            fields=[
                ('GameId', models.IntegerField(primary_key=True, serialize=False)),
                ('DateTime_UTC', models.DateTimeField()),
                ('Team1', models.CharField(max_length=255)),
                ('Team2', models.CharField(max_length=255)),
                ('Team1Score', models.IntegerField()),
                ('Team2Score', models.IntegerField()),
                ('Patch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('OverviewPage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreboardPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.scoreboardgames')),
            ],
        ),
        migrations.AddField(
            model_name='scoreboardgames',
            name='OverviewPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.tournaments'),
        ),
    ]
